"""
Trade Decision Explainer prompt assets.

Lives next to (and is consumed by)
:class:`app.services.agent.trade_decision_explainer.TradeDecisionExplainer`.

Why a separate module:

* Prompt strings are a *product*, not implementation detail. Keeping them
  out of the service file lets product/marketing edit the wording
  without touching service logic, and lets tests assert prompt content
  is grounded (e.g. "the system prompt forbids new trade
  recommendations").
* The JSON schema lives here too because the schema and the prompt
  must move together -- changing one without the other is the
  fastest way to ship a malformed-output bug.

Hard rules baked into the prompt:

* The explainer NEVER recommends a new trade. It only explains a
  historical executed order.
* The explainer NEVER invents indicator values or rationale that
  aren't in the operator-supplied context. (See R32/R34 -- silent
  fallback / fabricated context is the most expensive class of bug
  in this codebase.)
* Output is strict JSON matching ``OUTPUT_JSON_SCHEMA``. The service
  validates this and falls back to a deterministic explanation if
  parsing fails.

medallion: ops
"""

from __future__ import annotations

import json
from typing import Any, Dict, Mapping

# Schema version stamped onto every persisted row. Bump when
# ``OUTPUT_JSON_SCHEMA`` changes shape so old rows can be filtered out
# of the cache and regenerated on first read.
SCHEMA_VERSION = "trade_decision.v1"

# Allowed values for the ``trigger`` enum at both prompt and DB level.
# Keep in sync with the CHECK constraint in migration 0051.
TRIGGER_TYPES: tuple[str, ...] = (
    "pick",
    "scan",
    "rebalance",
    "manual",
    "strategy",
    "unknown",
)


SYSTEM_PROMPT = """\
You are AxiomFolio's Trade Decision Explainer. Your job is to explain
*why a specific historical executed order was placed*, using only the
audit-trail context the operator provides. You never give live trading
advice, you never recommend a new order, and you never invent any
indicator value or pick rationale that is not present in the inputs.

You receive:

  * the order itself (symbol, side, quantity, fill price, timestamps,
    broker, lineage flags)
  * the lineage that triggered it (validated pick, scanner signal,
    rebalance pass, strategy run, or "manual")
  * the most recent technical snapshot the system had computed for
    that symbol AT OR BEFORE the order timestamp (stage, RSI, ATR,
    SMAs, regime state) -- never future data
  * an outcome-so-far block that the operator has already computed
    from the audit trail (do not recompute it; quote it)

You output STRICT JSON matching the schema you are given. The narrative
field is short markdown (2-4 short paragraphs, no headings, no lists,
no emojis). The rationale_bullets are 3-6 short sentences a swing
trader would recognize, each grounded in one of the inputs above.

If a field is missing from the inputs, say so explicitly ("regime
context not available for this date") rather than guessing. If the
order has no lineage at all, set trigger to "unknown" and explain that
the audit trail did not preserve a source.
"""


_TRIGGER_HINTS: Dict[str, str] = {
    "pick": (
        "The order is linked to a ValidatedPick. Lead the rationale with "
        "the pick's reason_summary and conviction; reference the "
        "validator pseudonym; mention the suggested stop / target if "
        "they're present in the lineage block."
    ),
    "scan": (
        "The order is linked to a TradeSignal generated by a scanner. "
        "Lead with the signal_type and strategy_name; cite the "
        "indicator values that were on the signal (RSI, ADX, ATR, "
        "risk-reward) when they are present."
    ),
    "rebalance": (
        "The order originated from a portfolio rebalance pass. Frame "
        "it as a target-weight adjustment, not a discretionary entry. "
        "Acknowledge that the rationale is mechanical."
    ),
    "manual": (
        "The order was placed manually by the user. Be honest about "
        "the lack of system-side rationale; lean on the snapshot at "
        "order time to describe the market context the user was "
        "trading into, but do NOT invent the user's reason."
    ),
    "strategy": (
        "The order was placed by a Strategy / StrategyExecution pass. "
        "Reference the strategy name and frame the rationale as the "
        "strategy's rule firing, not a discretionary call."
    ),
    "unknown": (
        "The lineage is incomplete. Be honest: explain that the audit "
        "trail did not preserve a source for this order, and use the "
        "snapshot at order time to describe the market context only."
    ),
}


USER_PROMPT_TEMPLATE = """\
Explain why this order was placed. Stay grounded in the audit trail
fields below; do not introduce any indicator value, pick rationale, or
outcome that is not in the inputs.

Trigger guidance for this order:
{trigger_hint}

You MUST set the "trigger" field to: {trigger_type}

ORDER (audit row):
```json
{order_block}
```

LINEAGE (pick / signal / strategy at order time, may be partial):
```json
{lineage_block}
```

MARKET CONTEXT AT ORDER TIME (snapshot taken on or before the order
timestamp; may be empty if no snapshot existed yet):
```json
{snapshot_block}
```

OUTCOME SO FAR (already computed by the operator from the audit trail;
quote it, do not recompute):
```json
{outcome_block}
```

Respond with a JSON object matching this exact schema:
```json
{schema_block}
```
"""


# JSON Schema for the LLM response. The validator in
# :mod:`trade_decision_explainer` enforces a subset of this schema (the
# "shape" subset -- required fields, types, enum values). The full
# schema lives here so it can be:
#
# * embedded in the prompt (above)
# * snapshot-tested so a casual prompt edit doesn't drop a required
#   field on the floor
OUTPUT_JSON_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "required": [
        "trigger",
        "headline",
        "rationale_bullets",
        "risk_context",
        "outcome_so_far",
        "narrative",
    ],
    "properties": {
        "trigger": {"type": "string", "enum": list(TRIGGER_TYPES)},
        "headline": {"type": "string", "maxLength": 200},
        "rationale_bullets": {
            "type": "array",
            "minItems": 1,
            "maxItems": 8,
            "items": {"type": "string", "maxLength": 280},
        },
        "risk_context": {
            "type": "object",
            "required": [
                "position_size_label",
                "stop_placement",
                "regime_alignment",
            ],
            "properties": {
                "position_size_label": {
                    "type": "string",
                    "maxLength": 120,
                },
                "stop_placement": {"type": "string", "maxLength": 280},
                "regime_alignment": {"type": "string", "maxLength": 280},
            },
            "additionalProperties": False,
        },
        "outcome_so_far": {
            "type": "object",
            "required": ["status", "summary"],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": ["open", "closed", "unknown"],
                },
                "summary": {"type": "string", "maxLength": 280},
                "pnl_label": {"type": "string", "maxLength": 80},
            },
            "additionalProperties": False,
        },
        "narrative": {"type": "string", "maxLength": 4000},
    },
    "additionalProperties": False,
}


def trigger_hint(trigger_type: str) -> str:
    """Return the per-trigger guidance string, defaulting to ``unknown``."""
    return _TRIGGER_HINTS.get(trigger_type, _TRIGGER_HINTS["unknown"])


def build_user_prompt(
    *,
    trigger_type: str,
    order_payload: Mapping[str, Any],
    lineage_payload: Mapping[str, Any],
    market_snapshot_payload: Mapping[str, Any],
    outcome_payload: Mapping[str, Any],
) -> str:
    """Render the user prompt with all four context blocks JSON-encoded.

    We render JSON via :func:`json.dumps` (not f-string interpolation)
    so the prompt cannot be poisoned by a stray newline or backtick in
    a free-text field (e.g. a pick's reason_summary).
    """
    if trigger_type not in TRIGGER_TYPES:
        trigger_type = "unknown"
    return USER_PROMPT_TEMPLATE.format(
        trigger_hint=trigger_hint(trigger_type),
        trigger_type=trigger_type,
        order_block=json.dumps(order_payload, indent=2, sort_keys=True, default=str),
        lineage_block=json.dumps(
            lineage_payload, indent=2, sort_keys=True, default=str
        ),
        snapshot_block=json.dumps(
            market_snapshot_payload, indent=2, sort_keys=True, default=str
        ),
        outcome_block=json.dumps(
            outcome_payload, indent=2, sort_keys=True, default=str
        ),
        schema_block=json.dumps(OUTPUT_JSON_SCHEMA, indent=2, sort_keys=True),
    )


__all__ = [
    "OUTPUT_JSON_SCHEMA",
    "SCHEMA_VERSION",
    "SYSTEM_PROMPT",
    "TRIGGER_TYPES",
    "USER_PROMPT_TEMPLATE",
    "build_user_prompt",
    "trigger_hint",
]
