from __future__ import annotations

import json
import re
import subprocess
from datetime import UTC, datetime
from enum import StrEnum
from importlib import resources
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from pwl import find_monorepo_root
from pwl.template_engine import compute_context, render_template_tree

NAME_RE = re.compile(r"^[a-z][a-z0-9-]{2,40}$")
PR_TITLE = "feat(pwl): scaffold new API app"


class AppType(StrEnum):
    api = "api"
    web = "web"
    package = "package"


class Language(StrEnum):
    python = "python"
    typescript = "typescript"


def _target_path(name: str, app_type: AppType) -> Path:
    if app_type is AppType.web:
        return Path("apps") / name
    if app_type is AppType.package:
        return Path("packages") / name
    return Path("apis") / name


def _iso_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _validate_options(name: str, app_type: AppType, language: Language) -> None:
    if not NAME_RE.fullmatch(name):
        raise typer.BadParameter("name must match [a-z][a-z0-9-]{2,40}")
    if app_type is not AppType.api:
        raise typer.BadParameter("--type api is implemented in WS-59; web/package arrive in WS-60")
    if language is not Language.python:
        raise typer.BadParameter("--type api currently requires --language python")


def _git_user_name(root: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "config", "user.name"],
            cwd=root,
            capture_output=True,
            check=False,
            text=True,
        )
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _api_template_path() -> resources.abc.Traversable:
    return resources.files("pwl.templates").joinpath("app_skeleton", "api")


def _render_service_block(name: str, name_snake: str) -> str:
    start_command = (
        f"cd apis/{name} && gunicorn {name_snake}.main:app "
        "-k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    )
    return f"""
  # ---------------------------------------------------------------------
  # {name} API — generated by pwl new-app.
  # ---------------------------------------------------------------------
  - type: web
    name: {name}
    runtime: python
    region: oregon
    plan: starter
    buildCommand: cd apis/{name} && pip install .
    preDeployCommand: cd apis/{name} && alembic upgrade head
    startCommand: {start_command}
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: "3.11.0"
"""


def _append_render_service(root: Path, name: str, name_snake: str) -> Path:
    path = root / "render.yaml"
    block = _render_service_block(name, name_snake)

    if not path.exists():
        path.write_text(f"services:{block}")
        return path

    text = path.read_text()
    if f"\n    name: {name}\n" in text:
        raise RuntimeError(f"render.yaml already contains a service named {name}")
    if "services:" not in text:
        raise RuntimeError("render.yaml does not contain a services: section")

    databases_marker = "\ndatabases:"
    if databases_marker in text:
        updated = text.replace(databases_marker, f"{block}{databases_marker}", 1)
    else:
        updated = text.rstrip() + block + "\n"
    path.write_text(updated)
    return path


def _next_workstream_number(workstreams: list[dict[str, object]]) -> int:
    numbers: list[int] = []
    for workstream in workstreams:
        raw_id = workstream.get("id")
        if isinstance(raw_id, str):
            match = re.match(r"^WS-(\d{2,3})-", raw_id)
            if match:
                numbers.append(int(match.group(1)))
    return (max(numbers) + 1) if numbers else 1


def _next_free_priority(workstreams: list[dict[str, object]]) -> int:
    used = {item["priority"] for item in workstreams if isinstance(item.get("priority"), int)}
    priority = 0
    while priority in used:
        priority += 1
    return priority


def _append_workstream_entry(root: Path, name: str) -> Path:
    path = root / "apps" / "studio" / "src" / "data" / "workstreams.json"
    data = json.loads(path.read_text())
    workstreams = data.get("workstreams")
    if not isinstance(workstreams, list):
        raise RuntimeError("workstreams.json has no workstreams list")

    new_id = f"WS-{_next_workstream_number(workstreams):02d}-{name}-onboarding"
    if any(item.get("id") == new_id for item in workstreams if isinstance(item, dict)):
        raise RuntimeError(f"workstreams.json already contains {new_id}")

    now = _iso_now()
    workstreams.append(
        {
            "id": new_id,
            "title": f"Onboard {name} API service",
            "track": "Z",
            "priority": _next_free_priority(workstreams),
            "status": "pending",
            "percent_done": 0,
            "owner": "brain",
            "brief_tag": f"track:{name}-onboarding",
            "blockers": [],
            "last_pr": None,
            "last_activity": now,
            "last_dispatched_at": None,
            "notes": (
                f"Generated by pwl new-app {name}; create Vercel project link manually "
                "if a frontend is added."
            ),
            "estimated_pr_count": 1,
            "github_actions_workflow": None,
            "related_plan": "level_4_autonomy_+_platform",
        }
    )
    data["updated"] = now
    path.write_text(json.dumps(data, indent=2) + "\n")
    return path


def _current_branch(root: Path) -> str | None:
    result = subprocess.run(
        ["git", "branch", "--show-current"],
        cwd=root,
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _open_branch(root: Path, name: str) -> tuple[bool, str]:
    if not (root / ".git").exists():
        return False, "not a git checkout; skipped branch creation"

    branch = f"feat/new-app-{name}"
    if _current_branch(root) == branch:
        return True, f"already on {branch}"

    result = subprocess.run(
        ["git", "checkout", "-b", branch],
        cwd=root,
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"failed to create branch {branch}")
    return True, f"created {branch}"


def _run_auto_pr(root: Path, name: str, changed_paths: list[Path]) -> None:
    relative_paths = [str(path.relative_to(root)) for path in changed_paths]
    commands = [
        ["git", "add", *relative_paths],
        ["git", "commit", "-m", f"feat(pwl): scaffold {name} api app"],
        ["gh", "pr", "create", "--title", PR_TITLE, "--body", _pr_body(name)],
    ]
    for command in commands:
        result = subprocess.run(
            command,
            cwd=root,
            capture_output=True,
            check=False,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or f"command failed: {' '.join(command)}")


def _pr_body(name: str) -> str:
    return f"""## Summary
- Scaffold `{name}` FastAPI service from the pwl API template.
- Register Render service config and Studio workstream onboarding entry.

## Vercel link recommendation
No Vercel project was created automatically. If `{name}` later gets a frontend, run the
Vercel project link flow manually from the repo and commit only non-secret metadata.
"""


def new_app(
    name: Annotated[str, typer.Argument(help="New app slug, e.g. mortgage-intake.")],
    app_type: Annotated[
        AppType,
        typer.Option("--type", help="Kind of Paperwork app to scaffold."),
    ] = AppType.api,
    language: Annotated[
        Language,
        typer.Option("--language", help="Primary language for the scaffold."),
    ] = Language.python,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Print the planned scaffold without writing files."),
    ] = False,
    auto_pr: Annotated[
        bool,
        typer.Option("--auto-pr", help="Commit generated files and open a GitHub PR."),
    ] = False,
) -> None:
    """Create a new Paperwork API app from the bundled template."""
    _validate_options(name, app_type, language)

    console = Console()
    root = find_monorepo_root()
    if root is None:
        console.print("[red]Could not find a Paperwork monorepo root.[/red]")
        raise typer.Exit(1)

    target = root / _target_path(name, app_type)
    if target.exists():
        console.print(f"[red]{target.relative_to(root)} already exists.[/red]")
        raise typer.Exit(1)

    context = compute_context(name, author=_git_user_name(root))
    changed_paths = [
        target,
        root / "render.yaml",
        root / "apps" / "studio" / "src" / "data" / "workstreams.json",
    ]

    if dry_run:
        console.print(f"[cyan]DRY RUN[/cyan] would create {target.relative_to(root)}/")
        console.print("Would render template app_skeleton/api")
        console.print("Would append render.yaml service")
        console.print(
            "Would add Studio workstream entry "
            f"WS-{_next_workstream_number(_load_workstreams(root)):02d}-{name}-onboarding"
        )
        console.print("Would create branch feat/new-app-" + name)
        console.print(
            "Vercel recommendation: create/link a frontend project manually only when "
            "this API has a web app."
        )
        return

    try:
        branch_created, branch_message = _open_branch(root, name)
        with resources.as_file(_api_template_path()) as template_path:
            render_template_tree(template_path, target, context)
        render_path = _append_render_service(root, name, context["name_snake"])
        workstreams_path = _append_workstream_entry(root, name)
    except (OSError, RuntimeError, ValueError, KeyError) as exc:
        console.print(f"[red]new-app failed:[/red] {exc}")
        raise typer.Exit(1) from exc

    branch_prefix = "✓" if branch_created else "!"
    console.print(f"[green]{branch_prefix}[/green] {branch_message}")
    console.print(f"[green]✓[/green] created {target.relative_to(root)}/")
    console.print(f"[green]✓[/green] updated {render_path.relative_to(root)}")
    console.print(f"[green]✓[/green] updated {workstreams_path.relative_to(root)}")
    console.print(
        "[yellow]![/yellow] Vercel project not created; link manually if this service "
        "gets a frontend."
    )

    if auto_pr:
        try:
            _run_auto_pr(root, name, changed_paths)
        except RuntimeError as exc:
            console.print(f"[red]auto-pr failed:[/red] {exc}")
            raise typer.Exit(1) from exc
        console.print("[green]✓[/green] opened GitHub PR")


def _load_workstreams(root: Path) -> list[dict[str, object]]:
    path = root / "apps" / "studio" / "src" / "data" / "workstreams.json"
    data = json.loads(path.read_text())
    workstreams = data.get("workstreams")
    if not isinstance(workstreams, list):
        raise RuntimeError("workstreams.json has no workstreams list")
    return [item for item in workstreams if isinstance(item, dict)]
