import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { HelpCircle } from 'lucide-react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';
import { usePortfolioNarrativeLatest } from '../../hooks/usePortfolio';

const WHY_COPY =
  'This narrative is built from your open stock positions (top movers and day P&L), ' +
  'stage changes from daily MarketSnapshotHistory, ex-dividend records synced from your brokers, ' +
  'portfolio vs SPY one-day returns from PortfolioHistory and SPY snapshot performance, ' +
  'and the latest Market Regime (R1–R5) for the narrative date.';

export const DailyNarrative: React.FC = () => {
  const q = usePortfolioNarrativeLatest();

  if (q.isPending) {
    return (
      <Card className="border-border/80">
        <CardHeader className="pb-2">
          <div className="h-4 w-40 animate-pulse rounded bg-muted" />
        </CardHeader>
        <CardContent className="space-y-2">
          <div className="h-3 w-full animate-pulse rounded bg-muted" />
          <div className="h-3 w-[92%] animate-pulse rounded bg-muted" />
          <div className="h-3 w-[80%] animate-pulse rounded bg-muted" />
        </CardContent>
      </Card>
    );
  }

  if (q.isError) {
    return (
      <Card className="border-destructive/40">
        <CardContent className="pt-6 text-sm text-muted-foreground">
          Could not load your daily narrative.{' '}
          <button
            type="button"
            className="font-medium text-foreground underline underline-offset-2"
            onClick={() => q.refetch()}
          >
            Retry
          </button>
        </CardContent>
      </Card>
    );
  }

  if (q.data === null) {
    return (
      <Card className="border-border/80 bg-muted/20">
        <CardContent className="pt-6 text-sm text-muted-foreground">
          Your daily narrative will appear after market close. Check back tomorrow.
        </CardContent>
      </Card>
    );
  }

  const providerLabel = q.data.provider === 'openai' ? 'OpenAI' : q.data.provider;

  return (
    <TooltipProvider delayDuration={200}>
      <Card className="border-border/80">
        <CardHeader className="flex flex-row items-start justify-between gap-2 pb-2">
          <CardTitle className="font-heading text-base">What changed today</CardTitle>
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                type="button"
                className="inline-flex size-8 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                aria-label="Why you see this narrative"
              >
                <HelpCircle className="size-4" aria-hidden />
              </button>
            </TooltipTrigger>
            <TooltipContent side="left" className="max-w-xs text-xs leading-snug">
              {WHY_COPY}
            </TooltipContent>
          </Tooltip>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className={cn('text-sm leading-relaxed text-foreground', '[&_strong]:font-semibold [&_p]:my-2')}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{q.data.text}</ReactMarkdown>
          </div>
          <p className="text-xs text-muted-foreground">
            Generated by AI · {providerLabel}
            {q.data.is_fallback ? ' · template fallback' : ''}
          </p>
        </CardContent>
      </Card>
    </TooltipProvider>
  );
};
