import React from 'react';
import { describe, it, expect, vi, afterEach } from 'vitest';
import { cleanup, screen } from '@testing-library/react';

import { renderWithProviders } from '../../../test/render';
import { DailyNarrative } from '../DailyNarrative';

const mockUsePortfolioNarrativeLatest = vi.fn();

vi.mock('../../../hooks/usePortfolio', async () => {
  const actual = await vi.importActual<typeof import('../../../hooks/usePortfolio')>(
    '../../../hooks/usePortfolio',
  );
  return {
    ...actual,
    usePortfolioNarrativeLatest: () => mockUsePortfolioNarrativeLatest(),
  };
});

describe('DailyNarrative', () => {
  afterEach(() => {
    cleanup();
    vi.clearAllMocks();
  });

  it('shows skeleton while loading', () => {
    mockUsePortfolioNarrativeLatest.mockReturnValue({
      isPending: true,
      isError: false,
      isSuccess: false,
      data: undefined,
      refetch: vi.fn(),
    } as any);
    renderWithProviders(<DailyNarrative />);
    expect(document.querySelector('.animate-pulse')).toBeTruthy();
  });

  it('shows empty state on 404 payload', () => {
    mockUsePortfolioNarrativeLatest.mockReturnValue({
      isPending: false,
      isError: false,
      isSuccess: true,
      data: null,
      refetch: vi.fn(),
    } as any);
    renderWithProviders(<DailyNarrative />);
    expect(
      screen.getByText(/Your daily narrative will appear after market close/i),
    ).toBeInTheDocument();
  });

  it('renders markdown narrative', () => {
    mockUsePortfolioNarrativeLatest.mockReturnValue({
      isPending: false,
      isError: false,
      isSuccess: true,
      data: {
        date: '2026-04-15',
        text: 'Line with **bold**.',
        provider: 'openai',
        model: 'gpt-4o-mini',
        is_fallback: false,
        generated_at: '2026-04-15T21:00:00+00:00',
      },
      refetch: vi.fn(),
    } as any);
    renderWithProviders(<DailyNarrative />);
    expect(screen.getByText('What changed today')).toBeInTheDocument();
    expect(screen.getByText(/Generated by AI/i)).toBeInTheDocument();
  });
});
