"""Track C — Brain-owned proactive persona cadence.

Runs once per hour, checks every PersonaSpec for a ``proactive_cadence``
setting, and posts a brief ``Slack`` update to each persona's
``owner_channel`` when the schedule fires:

  - ``daily`` personas post at 14:00 UTC (≈7am PT / 9am ET) every weekday
  - ``weekly`` personas post Mondays at 15:00 UTC
  - ``monthly`` personas post on the 1st at 16:00 UTC

We keep state in Redis (``brain:cadence:last:{persona}`` → ISO date) so a
restart doesn't cause double-posts and so the hourly tick is idempotent.

The post is generated by running the persona itself through Brain with a
self-brief prompt. That gives the persona full access to memory, tools, and
its own tone prefix, so the output sounds like it actually came from that
employee instead of a canned template.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from apscheduler.triggers.cron import CronTrigger

from app.config import settings
from app.database import async_session_factory
from app.personas import list_specs
from app.redis import get_redis
from app.services import agent as brain_agent
from app.services import slack_outbound

logger = logging.getLogger(__name__)

_ORG_ID = "paperwork-labs"

# Slack channel slug → real channel ID. Keep in lockstep with
# `app/personas/routing.py::CHANNEL_PERSONA_MAP` (inverted). When we add
# a new persona with a new owner_channel, add the channel here too.
OWNER_CHANNEL_IDS: dict[str, str] = {
    "engineering": "C0ALLEKR9FZ",
    "ea": "C0AM01NHQ3Y",
    "strategy": "C0AM2310P8A",
    "social": "C0ALVG3EW1Z",
    "cpa": "C0APN01LDJN",
    "trading": "C0APFJSDB6X",
    # Personas that don't have a dedicated channel yet fall back to #general.
    "legal": "C0AM01NHQ3Y",
    "cfo": "C0AM01NHQ3Y",
    "qa": "C0AM01NHQ3Y",
    "tax": "C0APN01LDJN",
    "growth": "C0AM01NHQ3Y",
    "partnerships": "C0AM01NHQ3Y",
    "ux": "C0AM01NHQ3Y",
    "agent-ops": "C0AM01NHQ3Y",
}


def _cadence_prompt(persona: str, cadence: str) -> str:
    """The internal message we send as 'user input' to kick off a brief."""
    horizon = {
        "daily": "the last 24 hours and the next 24 hours",
        "weekly": "the last week and the week ahead",
        "monthly": "the last month and the month ahead",
    }.get(cadence, "the recent work")
    return (
        f"Proactive {cadence} brief for the #{persona.replace('-', '')} channel. "
        f"In 5-8 bullets max, cover {horizon}: wins, risks, decisions needed, "
        "and the single most important thing to act on. Speak as the persona, "
        "in your own voice. No preamble — jump straight to bullets."
    )


def _should_fire(cadence: str, now: datetime) -> bool:
    """Return True when this hour should trigger a post for ``cadence``.

    We key each cadence to a specific UTC hour so multiple personas within
    the same cadence cluster together (readable in Slack) without
    overlapping the PR-sweep window.
    """
    if cadence == "daily":
        return now.hour == 14 and now.weekday() < 5
    if cadence == "weekly":
        return now.weekday() == 0 and now.hour == 15
    if cadence == "monthly":
        return now.day == 1 and now.hour == 16
    return False


async def _already_posted_today(redis_client: Any, persona: str, today: str) -> bool:
    if redis_client is None:
        return False
    try:
        key = f"brain:cadence:last:{persona}"
        last = await redis_client.get(key)
        if last is None:
            return False
        last_str = last if isinstance(last, str) else last.decode("utf-8")
        return last_str == today
    except Exception:
        logger.debug("cadence redis lookup failed for %s", persona, exc_info=True)
        return False


async def _mark_posted(redis_client: Any, persona: str, today: str) -> None:
    if redis_client is None:
        return
    try:
        key = f"brain:cadence:last:{persona}"
        # Keep for 40 days so monthly cadences don't re-post on boot.
        await redis_client.setex(key, 60 * 60 * 24 * 40, today)
    except Exception:
        logger.debug("cadence redis setex failed for %s", persona, exc_info=True)


async def _post_for_persona(persona: str, cadence: str, channel_id: str) -> None:
    """Run Brain as ``persona`` and post the result to ``channel_id``."""
    redis_client = None
    try:
        redis_client = get_redis()
    except RuntimeError:
        pass

    async with async_session_factory() as db:
        result = await brain_agent.process(
            db,
            redis_client,
            organization_id=_ORG_ID,
            org_name="Paperwork Labs",
            user_id=f"brain-scheduler:{cadence}",
            message=_cadence_prompt(persona, cadence),
            channel="slack-scheduler",
            channel_id=channel_id,
            request_id=f"cadence:{persona}:{datetime.utcnow().date().isoformat()}",
            persona_pin=persona,
        )
        await db.commit()

    body = (result.get("response") or "").strip()
    if not body:
        logger.warning("cadence for %s returned empty; skipping Slack post", persona)
        return

    await slack_outbound.post_message(
        channel=channel_id,
        text=f"*{persona}* — {cadence} brief\n{body[:3500]}",
        unfurl_links=False,
    )


async def _run_cadence_tick() -> None:
    """Scheduled hourly task. Swallow everything; next hour retries."""
    now = datetime.now(timezone.utc)
    today = now.date().isoformat()

    redis_client = None
    try:
        redis_client = get_redis()
    except RuntimeError:
        pass

    for spec in list_specs():
        cadence = getattr(spec, "proactive_cadence", "never")
        if cadence == "never":
            continue
        if not _should_fire(cadence, now):
            continue
        if await _already_posted_today(redis_client, spec.name, today):
            continue

        channel_id = OWNER_CHANNEL_IDS.get(
            spec.owner_channel or spec.name,
            settings.SLACK_ENGINEERING_CHANNEL_ID,
        )
        if not channel_id:
            logger.info("cadence skip: no channel mapping for %s", spec.name)
            continue

        try:
            await _post_for_persona(spec.name, cadence, channel_id)
            await _mark_posted(redis_client, spec.name, today)
            logger.info("cadence fired: persona=%s cadence=%s", spec.name, cadence)
        except Exception:
            logger.exception("cadence run failed for %s", spec.name)


def install(scheduler) -> None:
    """Install the cadence job on the shared APScheduler instance.

    Called from ``schedulers/pr_sweep.start_scheduler`` after the PR sweep
    job is registered, so we have a single scheduler lifecycle instead of
    two.
    """
    scheduler.add_job(
        _run_cadence_tick,
        trigger=CronTrigger(minute=0, timezone="UTC"),
        id="proactive_cadence",
        name="Brain persona proactive cadence",
        max_instances=1,
        coalesce=True,
        replace_existing=True,
    )
    logger.info("APScheduler job 'proactive_cadence' registered (hourly UTC)")
