"""add_v4_stage_analysis_fields_and_regime_table

Revision ID: 1e0612af8a13
Revises: ca304cdf065a
Create Date: 2026-03-24 07:26:39.879021
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1e0612af8a13"
down_revision = 'ca304cdf065a'
branch_labels = None
depends_on = None


def _has_column(bind, table: str, column: str) -> bool:
    insp = sa.inspect(bind)
    return any(c["name"] == column for c in insp.get_columns(table))


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    # Baseline revision 95b8b27bb6d1 uses Base.metadata.create_all(); fresh DBs may
    # already have market_regime from that step before this revision runs.
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if "market_regime" not in insp.get_table_names():
        op.create_table('market_regime',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('as_of_date', sa.DateTime(), nullable=False),
        sa.Column('vix_spot', sa.Float(), nullable=True),
        sa.Column('vix3m_vix_ratio', sa.Float(), nullable=True),
        sa.Column('vvix_vix_ratio', sa.Float(), nullable=True),
        sa.Column('nh_nl', sa.Integer(), nullable=True),
        sa.Column('pct_above_200d', sa.Float(), nullable=True),
        sa.Column('pct_above_50d', sa.Float(), nullable=True),
        sa.Column('score_vix', sa.Float(), nullable=True),
        sa.Column('score_vix3m_vix', sa.Float(), nullable=True),
        sa.Column('score_vvix_vix', sa.Float(), nullable=True),
        sa.Column('score_nh_nl', sa.Float(), nullable=True),
        sa.Column('score_above_200d', sa.Float(), nullable=True),
        sa.Column('score_above_50d', sa.Float(), nullable=True),
        sa.Column('composite_score', sa.Float(), nullable=True),
        sa.Column('regime_state', sa.String(length=10), nullable=False),
        sa.Column('cash_floor_pct', sa.Float(), nullable=True),
        sa.Column('max_equity_exposure_pct', sa.Float(), nullable=True),
        sa.Column('regime_multiplier', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_regime_date', 'market_regime', ['as_of_date'], unique=False)
        op.create_index(op.f('ix_market_regime_as_of_date'), 'market_regime', ['as_of_date'], unique=True)
        op.create_index(op.f('ix_market_regime_id'), 'market_regime', ['id'], unique=False)

    snap_cols = [
        ('ext_pct', sa.Float()),
        ('sma150_slope', sa.Float()),
        ('sma50_slope', sa.Float()),
        ('ema10_dist_pct', sa.Float()),
        ('ema10_dist_n', sa.Float()),
        ('vol_ratio', sa.Float()),
        ('scan_tier', sa.String(length=20)),
        ('action_label', sa.String(length=10)),
        ('regime_state', sa.String(length=10)),
    ]
    for name, col in snap_cols:
        if not _has_column(bind, "market_snapshot", name):
            op.add_column("market_snapshot", sa.Column(name, col, nullable=True))
    for name, col in snap_cols:
        if not _has_column(bind, "market_snapshot_history", name):
            op.add_column("market_snapshot_history", sa.Column(name, col, nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_snapshot_history', 'regime_state')
    op.drop_column('market_snapshot_history', 'action_label')
    op.drop_column('market_snapshot_history', 'scan_tier')
    op.drop_column('market_snapshot_history', 'vol_ratio')
    op.drop_column('market_snapshot_history', 'ema10_dist_n')
    op.drop_column('market_snapshot_history', 'ema10_dist_pct')
    op.drop_column('market_snapshot_history', 'sma50_slope')
    op.drop_column('market_snapshot_history', 'sma150_slope')
    op.drop_column('market_snapshot_history', 'ext_pct')
    op.drop_column('market_snapshot', 'regime_state')
    op.drop_column('market_snapshot', 'action_label')
    op.drop_column('market_snapshot', 'scan_tier')
    op.drop_column('market_snapshot', 'vol_ratio')
    op.drop_column('market_snapshot', 'ema10_dist_n')
    op.drop_column('market_snapshot', 'ema10_dist_pct')
    op.drop_column('market_snapshot', 'sma50_slope')
    op.drop_column('market_snapshot', 'sma150_slope')
    op.drop_column('market_snapshot', 'ext_pct')
    op.drop_index(op.f('ix_market_regime_id'), table_name='market_regime')
    op.drop_index(op.f('ix_market_regime_as_of_date'), table_name='market_regime')
    op.drop_index('idx_regime_date', table_name='market_regime')
    op.drop_table('market_regime')
    # ### end Alembic commands ###



