# The 30-week SMA needs ~150 trading days and the 10-week slope shift
# needs ~50 more.  We load 250+ trading days (≈400 calendar days) before
# the backfill start so Weinstein stages are valid from the first row.
WEINSTEIN_WARMUP_CALENDAR_DAYS: int = 400

# Snapshot fundamental keys: name, sub_industry, then sector/industry/market_cap + extended.
# Use FUNDAMENTAL_FIELDS[:5] for core-with-name; FUNDAMENTAL_FIELDS[2:5] for core-only.
FUNDAMENTAL_FIELDS = (
    "name",
    "sub_industry",
    "sector",
    "industry",
    "market_cap",
    "pe_ttm",
    "peg_ttm",
    "roe",
    "eps_growth_yoy",
    "eps_growth_qoq",
    "revenue_growth_yoy",
    "revenue_growth_qoq",
    "dividend_yield",
    "beta",
    "analyst_rating",
    "next_earnings",
    "last_earnings",
)

SNAPSHOT_PREFERRED_COLUMNS = [
    "symbol",
    "analysis_type",
    "analysis_timestamp",
    "as_of_timestamp",
    "expiry_timestamp",
    "current_price",
    "market_cap",
    "pe_ttm",
    "peg_ttm",
    "roe",
    "eps_growth_yoy",
    "eps_growth_qoq",
    "revenue_growth_yoy",
    "revenue_growth_qoq",
    "dividend_yield",
    "beta",
    "analyst_rating",
    "last_earnings",
    "next_earnings",
    "sector",
    "industry",
    "sub_industry",
    "stage_label",
    "stage_label_5d_ago",
    "current_stage_days",
    "previous_stage_label",
    "previous_stage_days",
    "rs_mansfield_pct",
    "sma_10",
    "sma_5",
    "sma_14",
    "sma_21",
    "sma_50",
    "sma_100",
    "sma_150",
    "sma_200",
    "atr_14",
    "atr_30",
    "atrp_14",
    "atrp_30",
    "atr_distance",
    "atr_value",
    "atr_percent",
    "range_pos_20d",
    "range_pos_50d",
    "range_pos_52w",
    "rsi",
    "macd",
    "macd_signal",
]

SNAPSHOTS_PREFERRED_COLUMNS = [
    "symbol",
    "analysis_timestamp",
    "as_of_timestamp",
    "current_price",
    "market_cap",
    "pe_ttm",
    "peg_ttm",
    "roe",
    "eps_growth_yoy",
    "eps_growth_qoq",
    "revenue_growth_yoy",
    "revenue_growth_qoq",
    "dividend_yield",
    "beta",
    "analyst_rating",
    "last_earnings",
    "next_earnings",
    "sector",
    "industry",
    "sub_industry",
    "stage_label",
    "stage_label_5d_ago",
    "current_stage_days",
    "previous_stage_label",
    "previous_stage_days",
    "rs_mansfield_pct",
    "sma_10",
    "sma_5",
    "sma_14",
    "sma_21",
    "sma_50",
    "sma_100",
    "sma_150",
    "sma_200",
    "ema_8",
    "ema_21",
    "atr_14",
    "atr_30",
    "atrp_14",
    "atrp_30",
    "range_pos_20d",
    "range_pos_50d",
    "range_pos_52w",
    "atrx_sma_21",
    "atrx_sma_50",
    "atrx_sma_100",
    "atrx_sma_150",
    "rsi",
    "macd",
    "macd_signal",
    "perf_1d",
    "perf_5d",
    "perf_20d",
]

SNAPSHOT_HISTORY_PREFERRED_COLUMNS = [
    "symbol",
    "analysis_type",
    "analysis_timestamp",
    "as_of_date",
    "current_price",
    "market_cap",
    "pe_ttm",
    "peg_ttm",
    "roe",
    "eps_growth_yoy",
    "eps_growth_qoq",
    "revenue_growth_yoy",
    "revenue_growth_qoq",
    "dividend_yield",
    "beta",
    "analyst_rating",
    "last_earnings",
    "next_earnings",
    "sector",
    "industry",
    "sub_industry",
    "stage_label",
    "stage_label_5d_ago",
    "current_stage_days",
    "previous_stage_label",
    "previous_stage_days",
    "rs_mansfield_pct",
    "sma_10",
    "sma_5",
    "sma_14",
    "sma_21",
    "sma_50",
    "sma_100",
    "sma_150",
    "sma_200",
    "atr_14",
    "atr_30",
    "atrp_14",
    "atrp_30",
    "atr_distance",
    "atr_value",
    "atr_percent",
    "range_pos_20d",
    "range_pos_50d",
    "range_pos_52w",
    "rsi",
    "macd",
    "macd_signal",
]
"""Market service constants and curated symbol sets."""

POPULAR_STOCKS = [
    # Tech Giants
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "META",
    "TSLA",
    "NVDA",
    "NFLX",
    "CRM",
    "ORCL",
    # Financial
    "JPM",
    "BAC",
    "WFC",
    "GS",
    "MS",
    "C",
    "BLK",
    "AXP",
    "V",
    "MA",
    # Healthcare
    "JNJ",
    "PFE",
    "UNH",
    "MRK",
    "ABBV",
    "TMO",
    "MDT",
    "BMY",
    "AMGN",
    "GILD",
    # Consumer
    "KO",
    "PEP",
    "WMT",
    "TGT",
    "HD",
    "LOW",
    "MCD",
    "SBUX",
    "NKE",
    "DIS",
    # Industrial
    "BA",
    "CAT",
    "GE",
    "MMM",
    "UPS",
    "FDX",
    "HON",
    "LMT",
    "RTX",
    "DE",
    # Energy
    "XOM",
    "CVX",
    "COP",
    "EOG",
    "SLB",
    "PSX",
    "VLO",
    "MPC",
    "OXY",
    "HAL",
    # Communications
    "VZ",
    "T",
    "CMCSA",
    "CHTR",
    "TMUS",
    "DISH",
    # Real Estate
    "AMT",
    "PLD",
    "CCI",
    "EQIX",
    "SPG",
    "O",
    "WELL",
    "AVB",
    "EQR",
    "BXP",
    # Utilities
    "NEE",
    "DUK",
    "SO",
    "D",
    "AEP",
    "EXC",
    "XEL",
    "ED",
    "ETR",
    "ES",
    # Materials
    "LIN",
    "APD",
    "SHW",
    "ECL",
    "FCX",
    "NEM",
    "DOW",
    "DD",
    "PPG",
    "IFF",
    # Technology
    "ADBE",
    "INTC",
    "CSCO",
    "IBM",
    "QCOM",
    "TXN",
    "AVGO",
    "MU",
    "AMD",
    "NOW",
]

# Curated ETFs/index proxies that should always be present in tracked market views.
# These complement index constituents and portfolio-derived symbols.
CURATED_MARKET_SYMBOLS = [
    "COLO",
    "DBA",
    "DIA",
    "ECH",
    "EPOL",
    "EPU",
    "EWA",
    "EWC",
    "EWG",
    "EWH",
    "EWI",
    "EWJ",
    "EWM",
    "EWW",
    "EWY",
    "EWZ",
    "FUTY",
    "FXU",
    "GII",
    "GLD",
    "GREK",
    "IDU",
    "IFRA",
    "IHI",
    "INDA",
    "ITA",
    "ITB",
    "IWC",
    "IWM",
    "IYR",
    "IYT",
    "JXI",
    "MDY",
    "MOO",
    "NFRA",
    "OIH",
    "PALL",
    "PAVE",
    "PPLT",
    "RSPU",
    "SDP",
    "SHLD",
    # Use tradable semiconductor ETF proxy; SOX index symbol is not consistently
    # available across providers in our ingest stack.
    "SOXX",
    "SPSM",
    "SPY",
    "UPW",
    "USO",
    "UTES",
    "VPU",
    "XBI",
    "XHB",
    "XLB",
    "XLC",
    "XLE",
    "XLF",
    "XLI",
    "XLK",
    "XLP",
    "XLU",
    "XLV",
    "XLY",
    "XME",
    "XOP",
    "XRT",
]

# Sector ETF mapping for the market dashboard sector-rotation table.
SECTOR_ETF_SYMBOLS_ORDER: list[str] = [
    "XLE",
    "XLK",
    "XLC",
    "XLB",
    "XLF",
    "XLI",
    "XLP",
    "XRT",
    "XLV",
    "XLU",
    "XLY",
    "XME",
    "XHB",
    "SOX",
]

SECTOR_ETF_DISPLAY_NAMES: dict[str, str] = {
    "XLE": "Energy",
    "XLK": "Technology",
    "XLC": "Communication Services",
    "XLB": "Materials",
    "XLF": "Financial Services",
    "XLI": "Industrials",
    "XLP": "Consumer Staples",
    "XRT": "Retail",
    "XLV": "Healthcare",
    "XLU": "Utilities",
    "XLY": "Consumer Discretionary",
    "XME": "Metals & Mining",
    "XHB": "Homebuilders",
    "SOX": "Semiconductors",
}

# Some index symbols aren't available from all providers; map them to
# tradable ETF proxies so the dashboard always has data to show.
SECTOR_ETF_PROXY_SYMBOLS: dict[str, list[str]] = {
    "SOX": ["SOX", "SOXX"],
}
