"""
Construction helpers for :class:`AnomalyExplainer`.

These exist so Celery tasks and FastAPI routes never instantiate the
explainer ad-hoc -- both code paths must build it the same way (same
runbook, same task allowlist, same provider selection rules) so an
explanation generated by the auto-remediator and one generated on demand
from the admin UI are directly comparable.

Provider selection
------------------

* :data:`backend.config.settings.OPENAI_API_KEY` set
  -> :class:`OpenAIChatProvider` with the configured model
  (``settings.OPENAI_MODEL`` or ``"gpt-4o-mini"``).
* Otherwise -> :class:`StubLLMProvider` so the explainer still produces
  a deterministic-fallback explanation rather than crashing in dev /
  test / instances without the key.

Runbook loading is cached at module level (see :func:`get_runbook`) so
we don't re-read MARKET_DATA_RUNBOOK.md on every Celery task invocation.
The cache is keyed by mtime so a runbook edit on disk is picked up
without a process restart in dev (in prod the file is baked into the
image so the mtime is stable).

medallion: ops
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from threading import Lock
from typing import Mapping, Optional, Tuple

from .explainer import AnomalyExplainer
from .knowledge import RunbookKnowledge, load_runbook_chunks
from .openai_provider import OpenAIChatProvider
from .provider import LLMProvider, StubLLMProvider

logger = logging.getLogger(__name__)

_RUNBOOK_PATH_DEFAULT = Path(__file__).resolve().parents[4] / "docs" / "MARKET_DATA_RUNBOOK.md"

_runbook_cache_lock = Lock()
_runbook_cache: Optional[Tuple[float, RunbookKnowledge]] = None


def get_runbook(path: Optional[Path] = None) -> RunbookKnowledge:
    """Return a memoized :class:`RunbookKnowledge` for the runbook file.

    Re-loads when the file's mtime changes so editors see fresh content
    without restarting Celery. Falls back to an empty knowledge base if
    the file is missing -- the explainer copes with that by skipping
    runbook grounding entirely.
    """
    global _runbook_cache
    runbook_path = path or _RUNBOOK_PATH_DEFAULT
    if not runbook_path.exists():
        logger.warning(
            "anomaly_explainer.factory: runbook not found at %s; "
            "explanations will run without runbook grounding.",
            runbook_path,
        )
        return RunbookKnowledge(chunks=[])

    mtime = runbook_path.stat().st_mtime
    with _runbook_cache_lock:
        if _runbook_cache is not None and _runbook_cache[0] == mtime:
            return _runbook_cache[1]
        try:
            chunks = load_runbook_chunks(runbook_path)
        except Exception as exc:  # noqa: BLE001 - never block AutoOps on a parse error
            logger.warning(
                "anomaly_explainer.factory: failed to parse runbook at %s: %s",
                runbook_path,
                exc,
            )
            return RunbookKnowledge(chunks=[])
        knowledge = RunbookKnowledge(chunks=chunks)
        _runbook_cache = (mtime, knowledge)
        return knowledge


def _build_provider() -> LLMProvider:
    """Pick the best available LLM provider based on env config."""
    try:
        from app.config import settings
    except ImportError:  # tests can call this without settings wired
        return StubLLMProvider()

    api_key = getattr(settings, "OPENAI_API_KEY", None) or os.getenv("OPENAI_API_KEY")
    if not api_key:
        return StubLLMProvider()
    model = (
        getattr(settings, "ANOMALY_EXPLAINER_MODEL", None)
        or getattr(settings, "OPENAI_MODEL", None)
        or "gpt-4o-mini"
    )
    try:
        return OpenAIChatProvider(api_key=api_key, model=model)
    except Exception as exc:  # noqa: BLE001 -- degrade, don't crash AutoOps
        logger.warning(
            "anomaly_explainer.factory: failed to construct OpenAIChatProvider "
            "(%s); falling back to StubLLMProvider.",
            exc,
        )
        return StubLLMProvider()


def _default_task_allowlist() -> Mapping[str, str]:
    """Map of Celery task names the explainer is allowed to recommend.

    Sourced from :data:`app.tasks.ops.auto_ops.REMEDIATION_MAP` so the
    allowlist stays in lockstep with what the rule-based remediator can
    actually dispatch. Imported lazily to keep this module free of any
    Celery-side dependencies (handy for unit tests).
    """
    try:
        from app.tasks.ops.auto_ops import REMEDIATION_MAP
    except Exception:  # noqa: BLE001 - tests / scripts may run without celery
        return {}
    return {
        task_name: f"AutoOps remediation for {dimension!r}"
        for dimension, tasks in REMEDIATION_MAP.items()
        for task_name, _kwargs in tasks
    }


def build_default_explainer(
    *,
    provider: Optional[LLMProvider] = None,
    knowledge: Optional[RunbookKnowledge] = None,
    available_tasks: Optional[Mapping[str, str]] = None,
) -> AnomalyExplainer:
    """Construct the canonical AnomalyExplainer used by tasks + routes.

    Overrides exist purely for tests; production callers pass nothing.
    """
    return AnomalyExplainer(
        provider=provider or _build_provider(),
        knowledge=knowledge or get_runbook(),
        available_tasks=available_tasks if available_tasks is not None else _default_task_allowlist(),
    )


__all__ = [
    "build_default_explainer",
    "get_runbook",
]
