"use client";

// Buffer Week 4 — renders n8n workflow DAGs in /admin/workflows?tab=graph.
//
// Reads the static snapshot at src/data/n8n-graph.json (generated by
// scripts/snapshot_n8n_graphs.py, refreshed nightly by CI). No runtime
// dependency on the live n8n instance. When a workflow calls Paperwork
// Brain with a persona_pin, that pin is highlighted on the node so
// operators can see at a glance which persona runs this wiring.

import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import type { Edge, Node } from "@xyflow/react";
import { X } from "lucide-react";

import graph from "@/data/n8n-graph.json";
import type { CardNodeData, DagTone } from "@/components/dag/InteractiveDag";

const InteractiveDag = dynamic(
  () =>
    import("@/components/dag/InteractiveDag").then((mod) => mod.InteractiveDag),
  {
    ssr: false,
    loading: () => (
      <div className="flex min-h-[240px] items-center justify-center rounded-lg border border-zinc-800 bg-zinc-950 text-xs text-zinc-500">
        Loading workflow graph…
      </div>
    ),
  },
);

type WorkflowNode = {
  id: string;
  name: string;
  type: string;
  x: number;
  y: number;
};

type WorkflowEdge = {
  from: string;
  to: string;
};

type WorkflowGraph = {
  name: string;
  file: string;
  node_count: number;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  pattern: string;
  calls_brain: boolean;
  persona_pin: string | null;
};

type Snapshot = {
  content_hash?: string;
  generated_at?: string;
  source: string;
  workflows: WorkflowGraph[];
};

const snapshot = graph as Snapshot;

function shortType(type: string): string {
  const parts = type.split(".");
  return parts[parts.length - 1] || type;
}

function n8nTypeToTone(type: string): DagTone {
  const t = type.toLowerCase();
  if (t.includes("webhook")) return "webhook";
  if (t.includes("schedule") || t.includes("cron")) return "schedule";
  if (t.includes("httprequest")) return "http";
  if (t.includes("langchain") && t.includes("openai")) return "ai";
  if (t.includes("openai")) return "ai";
  if (t.includes("code") || t.includes("function")) return "code";
  if (t.includes("slack")) return "data";
  return "default";
}

function badgeToneClass(tone: DagTone): string {
  switch (tone) {
    case "webhook":
      return "bg-emerald-500/20 text-emerald-200 ring-emerald-500/40";
    case "schedule":
      return "bg-amber-500/20 text-amber-200 ring-amber-500/40";
    case "http":
      return "bg-sky-500/20 text-sky-200 ring-sky-500/40";
    case "ai":
      return "bg-violet-500/20 text-violet-200 ring-violet-500/40";
    case "code":
      return "bg-zinc-700/50 text-zinc-200 ring-zinc-600";
    case "data":
      return "bg-purple-500/20 text-purple-200 ring-purple-500/40";
    default:
      return "bg-zinc-800 text-zinc-300 ring-zinc-700";
  }
}

function patternLabel(pattern: string): string {
  if (pattern === "webhook") return "Webhook-triggered";
  if (pattern === "schedule") return "Scheduled (cron)";
  if (pattern === "manual") return "Manual-only";
  return "Unknown trigger";
}

function workflowToFlow(
  wf: WorkflowGraph,
  compact: boolean,
): { nodes: Node<CardNodeData, "card">[]; edges: Edge[] } {
  const nameToId = new Map(wf.nodes.map((n) => [n.name, n.id]));
  const nodes: Node<CardNodeData, "card">[] = wf.nodes.map((n) => ({
    id: n.id,
    type: "card",
    position: { x: 0, y: 0 },
    data: {
      label: n.name,
      subtitle: shortType(n.type),
      tone: n8nTypeToTone(n.type),
      compact,
    },
  }));

  const edges: Edge[] = [];
  wf.edges.forEach((e, i) => {
    const src = nameToId.get(e.from);
    const tgt = nameToId.get(e.to);
    if (src && tgt) {
      edges.push({
        id: `${wf.file}-e-${i}`,
        source: src,
        target: tgt,
        style: { stroke: "rgb(113 113 122)", strokeWidth: 1.5 },
      });
    }
  });

  return { nodes, edges };
}

function WorkflowDagPanel({
  wf,
  compact,
  showMiniMap,
  className,
}: {
  wf: WorkflowGraph;
  compact: boolean;
  showMiniMap: boolean;
  className?: string;
}) {
  const { nodes, edges } = useMemo(
    () => workflowToFlow(wf, compact),
    [wf, compact],
  );

  if (wf.nodes.length === 0) {
    return (
      <p className="text-xs italic text-zinc-500">No nodes in this workflow snapshot.</p>
    );
  }

  return (
    <InteractiveDag
      nodes={nodes}
      edges={edges}
      direction="TB"
      showMiniMap={showMiniMap}
      fitViewPadding={0.15}
      animateEdges={false}
      className={className}
    />
  );
}

function DagZoomModal({
  wf,
  onClose,
}: {
  wf: WorkflowGraph;
  onClose: () => void;
}) {
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-label={`Expanded graph: ${wf.name}`}
    >
      <div
        className="relative flex h-[88vh] w-full max-w-6xl flex-col overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="flex items-start justify-between gap-3 border-b border-zinc-800 px-5 py-3">
          <div className="min-w-0">
            <h3 className="truncate text-base font-semibold text-zinc-100">
              {wf.name}
            </h3>
            <p className="mt-0.5 text-xs text-zinc-500">
              {wf.file} · {wf.node_count} nodes ·{" "}
              {wf.calls_brain ? "calls Brain" : "no Brain call"}
              {wf.persona_pin ? ` · persona: ${wf.persona_pin}` : ""}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Link
              href={`https://github.com/paperwork-labs/paperwork/blob/main/infra/hetzner/workflows/${wf.file}`}
              target="_blank"
              rel="noreferrer"
              className="rounded-md border border-zinc-800 bg-zinc-900/60 px-2 py-1 text-[11px] text-zinc-300 transition hover:border-zinc-700 hover:text-zinc-100"
            >
              source ↗
            </Link>
            <button
              type="button"
              onClick={onClose}
              className="rounded-md p-1.5 text-zinc-400 transition hover:bg-zinc-800 hover:text-zinc-100"
              aria-label="Close zoom view"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </header>
        <div className="flex min-h-0 flex-1 flex-col p-4">
          <WorkflowDagPanel wf={wf} compact={false} showMiniMap className="min-h-0 flex-1 border-0" />
        </div>
        <footer className="border-t border-zinc-800 px-5 py-2 text-[11px] text-zinc-500">
          Press{" "}
          <kbd className="rounded bg-zinc-800 px-1 py-0.5 font-mono">Esc</kbd> or
          click outside to close.
        </footer>
      </div>
    </div>
  );
}

export function N8nGraphList() {
  const [query, setQuery] = useState("");
  const [brainOnly, setBrainOnly] = useState(false);
  const [zoomFile, setZoomFile] = useState<string | null>(null);
  const workflows = snapshot.workflows;
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return workflows.filter((w) => {
      if (brainOnly && !w.calls_brain) return false;
      if (!q) return true;
      return (
        w.name.toLowerCase().includes(q) ||
        w.file.toLowerCase().includes(q) ||
        (w.persona_pin ?? "").toLowerCase().includes(q)
      );
    });
  }, [workflows, query, brainOnly]);

  const brainCount = workflows.filter((w) => w.calls_brain).length;

  return (
    <section className="space-y-4">
      <header className="flex flex-col gap-3 rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="space-y-1">
          <p className="text-sm font-medium text-zinc-200">
            {workflows.length} n8n workflows — {brainCount} call Paperwork Brain
          </p>
          <p className="text-xs text-zinc-500">
            Snapshot:{" "}
            {snapshot.generated_at
              ? new Date(snapshot.generated_at).toLocaleString()
              : `content ${snapshot.content_hash ?? "unknown"}`}
            . Refresh with{" "}
            <code className="rounded bg-zinc-800 px-1">
              python scripts/snapshot_n8n_graphs.py
            </code>
            .
          </p>
        </div>
        <div className="flex items-center gap-2">
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Filter by name, file, or persona…"
            className="w-60 rounded-md border border-zinc-800 bg-zinc-950 px-2 py-1 text-xs text-zinc-200 placeholder:text-zinc-500 focus:border-zinc-600 focus:outline-none"
          />
          <label className="flex items-center gap-1 text-xs text-zinc-400">
            <input
              type="checkbox"
              checked={brainOnly}
              onChange={(e) => setBrainOnly(e.target.checked)}
              className="accent-zinc-300"
            />
            Brain callers only
          </label>
        </div>
      </header>

      {filtered.length === 0 && (
        <p className="rounded-xl border border-dashed border-zinc-800 bg-zinc-900/30 p-6 text-center text-xs text-zinc-500">
          No workflows match this filter.
        </p>
      )}

      <ul className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {filtered.map((wf) => (
          <li
            key={wf.file}
            className="space-y-3 rounded-xl border border-zinc-800 bg-zinc-900/40 p-4"
          >
            <div className="flex items-start justify-between gap-2">
              <div className="min-w-0 flex-1">
                <h3 className="truncate text-sm font-semibold text-zinc-100">
                  {wf.name}
                </h3>
                <p className="mt-0.5 text-[11px] text-zinc-500">
                  {wf.file} · {wf.node_count} nodes · {patternLabel(wf.pattern)}
                </p>
              </div>
              <div className="flex shrink-0 flex-wrap items-center gap-1">
                {wf.calls_brain && (
                  <span
                    className={`rounded-full px-2 py-0.5 text-[10px] font-medium ring-1 ${badgeToneClass("http")}`}
                  >
                    Brain
                  </span>
                )}
                {wf.persona_pin && (
                  <span
                    className={`rounded-full px-2 py-0.5 text-[10px] font-medium ring-1 ${badgeToneClass("code")}`}
                  >
                    persona: {wf.persona_pin}
                  </span>
                )}
              </div>
            </div>

            <div className="rounded-lg border border-zinc-800 bg-zinc-950/40 p-2">
              <div className="flex h-[320px] w-full flex-col">
                <WorkflowDagPanel
                  wf={wf}
                  compact
                  showMiniMap={false}
                  className="min-h-0 flex-1 !border-0"
                />
              </div>
            </div>

            <div className="flex flex-wrap gap-1 text-[10px] text-zinc-500">
              {Array.from(new Set(wf.nodes.map((n) => shortType(n.type)))).map(
                (t) => (
                  <span
                    key={t}
                    className={`rounded px-1.5 py-0.5 ring-1 ${badgeToneClass(n8nTypeToTone(`n8n-nodes-base.${t}`))}`}
                  >
                    {t}
                  </span>
                ),
              )}
            </div>

            <div className="flex items-center justify-between text-[11px]">
              <Link
                href={`https://github.com/paperwork-labs/paperwork/blob/main/infra/hetzner/workflows/${wf.file}`}
                target="_blank"
                rel="noreferrer"
                className="text-zinc-400 underline-offset-2 hover:text-zinc-200 hover:underline"
              >
                View source on GitHub ↗
              </Link>
              <button
                type="button"
                onClick={() => setZoomFile(wf.file)}
                className="rounded-md border border-zinc-800 bg-zinc-900/60 px-2 py-1 text-zinc-300 transition hover:border-zinc-700 hover:text-zinc-100"
              >
                Expand graph
              </button>
            </div>
          </li>
        ))}
      </ul>

      {zoomFile &&
        (() => {
          const wf = workflows.find((w) => w.file === zoomFile);
          if (!wf) return null;
          return <DagZoomModal wf={wf} onClose={() => setZoomFile(null)} />;
        })()}
    </section>
  );
}
